### UTAMI TRISNA KINANTI 2501782 1C RPL

### SOAL 3 

# PAK RENDI 

a = int(input("MASUKKAN JUMLAH MENIT YANG INGIN DI KONVERSI : "))
b = int(input("MASUKKAN JUMLAH DETIK YANG INGIN DI KONVERSI : "))

c = 60 * a + b 

print('JUMLAH WAKTUMU SETELAH DI KONVERSI ADALAH', c, "DETIK")

